# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: handsDet/calculators/util/collection_has_min_size_calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from handsDet.framework import calculator_pb2 as handsDet_dot_framework_dot_calculator__pb2
try:
  handsDet_dot_framework_dot_calculator__options__pb2 = handsDet_dot_framework_dot_calculator__pb2.handsDet_dot_framework_dot_calculator__options__pb2
except AttributeError:
  handsDet_dot_framework_dot_calculator__options__pb2 = handsDet_dot_framework_dot_calculator__pb2.handsDet.framework.calculator_options_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='handsDet/calculators/util/collection_has_min_size_calculator.proto',
  package='handsDet',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\nChandsDet/calculators/util/collection_has_min_size_calculator.proto\x12\thandsDet\x1a$handsDet/framework/calculator.proto\"\x9c\x01\n%CollectionHasMinSizeCalculatorOptions\x12\x13\n\x08min_size\x18\x01 \x01(\x05:\x01\x30\x32^\n\x03\x65xt\x12\x1c.handsDet.CalculatorOptions\x18\xd0\xb1\xd8{ \x01(\x0b\x32\x30.handsDet.CollectionHasMinSizeCalculatorOptions')
  ,
  dependencies=[handsDet_dot_framework_dot_calculator__pb2.DESCRIPTOR,])




_COLLECTIONHASMINSIZECALCULATOROPTIONS = _descriptor.Descriptor(
  name='CollectionHasMinSizeCalculatorOptions',
  full_name='handsDet.CollectionHasMinSizeCalculatorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min_size', full_name='handsDet.CollectionHasMinSizeCalculatorOptions.min_size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='handsDet.CollectionHasMinSizeCalculatorOptions.ext', index=0,
      number=259397840, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=277,
)

DESCRIPTOR.message_types_by_name['CollectionHasMinSizeCalculatorOptions'] = _COLLECTIONHASMINSIZECALCULATOROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CollectionHasMinSizeCalculatorOptions = _reflection.GeneratedProtocolMessageType('CollectionHasMinSizeCalculatorOptions', (_message.Message,), dict(
  DESCRIPTOR = _COLLECTIONHASMINSIZECALCULATOROPTIONS,
  __module__ = 'handsDet.calculators.util.collection_has_min_size_calculator_pb2'
  # @@protoc_insertion_point(class_scope:handsDet.CollectionHasMinSizeCalculatorOptions)
  ))
_sym_db.RegisterMessage(CollectionHasMinSizeCalculatorOptions)

_COLLECTIONHASMINSIZECALCULATOROPTIONS.extensions_by_name['ext'].message_type = _COLLECTIONHASMINSIZECALCULATOROPTIONS
handsDet_dot_framework_dot_calculator__options__pb2.CalculatorOptions.RegisterExtension(_COLLECTIONHASMINSIZECALCULATOROPTIONS.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
