# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: handsDet/calculators/util/landmarks_to_floats_calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from handsDet.framework import calculator_pb2 as handsDet_dot_framework_dot_calculator__pb2
try:
  handsDet_dot_framework_dot_calculator__options__pb2 = handsDet_dot_framework_dot_calculator__pb2.handsDet_dot_framework_dot_calculator__options__pb2
except AttributeError:
  handsDet_dot_framework_dot_calculator__options__pb2 = handsDet_dot_framework_dot_calculator__pb2.handsDet.framework.calculator_options_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='handsDet/calculators/util/landmarks_to_floats_calculator.proto',
  package='handsDet',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n?handsDet/calculators/util/landmarks_to_floats_calculator.proto\x12\thandsDet\x1a$handsDet/framework/calculator.proto\"\x9d\x01\n\"LandmarksToFloatsCalculatorOptions\x12\x19\n\x0enum_dimensions\x18\x01 \x01(\x05:\x01\x32\x32\\\n\x03\x65xt\x12\x1c.handsDet.CalculatorOptions\x18\xcc\xe7\xd5\x82\x01 \x01(\x0b\x32-.handsDet.LandmarksToFloatsCalculatorOptions')
  ,
  dependencies=[handsDet_dot_framework_dot_calculator__pb2.DESCRIPTOR,])




_LANDMARKSTOFLOATSCALCULATOROPTIONS = _descriptor.Descriptor(
  name='LandmarksToFloatsCalculatorOptions',
  full_name='handsDet.LandmarksToFloatsCalculatorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_dimensions', full_name='handsDet.LandmarksToFloatsCalculatorOptions.num_dimensions', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='handsDet.LandmarksToFloatsCalculatorOptions.ext', index=0,
      number=274035660, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=274,
)

DESCRIPTOR.message_types_by_name['LandmarksToFloatsCalculatorOptions'] = _LANDMARKSTOFLOATSCALCULATOROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LandmarksToFloatsCalculatorOptions = _reflection.GeneratedProtocolMessageType('LandmarksToFloatsCalculatorOptions', (_message.Message,), dict(
  DESCRIPTOR = _LANDMARKSTOFLOATSCALCULATOROPTIONS,
  __module__ = 'handsDet.calculators.util.landmarks_to_floats_calculator_pb2'
  # @@protoc_insertion_point(class_scope:handsDet.LandmarksToFloatsCalculatorOptions)
  ))
_sym_db.RegisterMessage(LandmarksToFloatsCalculatorOptions)

_LANDMARKSTOFLOATSCALCULATOROPTIONS.extensions_by_name['ext'].message_type = _LANDMARKSTOFLOATSCALCULATOROPTIONS
handsDet_dot_framework_dot_calculator__options__pb2.CalculatorOptions.RegisterExtension(_LANDMARKSTOFLOATSCALCULATOROPTIONS.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
