# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: handsDet/calculators/util/packet_frequency_calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from handsDet.framework import calculator_pb2 as handsDet_dot_framework_dot_calculator__pb2
try:
  handsDet_dot_framework_dot_calculator__options__pb2 = handsDet_dot_framework_dot_calculator__pb2.handsDet_dot_framework_dot_calculator__options__pb2
except AttributeError:
  handsDet_dot_framework_dot_calculator__options__pb2 = handsDet_dot_framework_dot_calculator__pb2.handsDet.framework.calculator_options_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='handsDet/calculators/util/packet_frequency_calculator.proto',
  package='handsDet',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n<handsDet/calculators/util/packet_frequency_calculator.proto\x12\thandsDet\x1a$handsDet/framework/calculator.proto\"\xa8\x01\n PacketFrequencyCalculatorOptions\x12\x1a\n\x0ftime_window_sec\x18\x01 \x01(\x01:\x01\x33\x12\r\n\x05label\x18\x02 \x03(\t2Y\n\x03\x65xt\x12\x1c.handsDet.CalculatorOptions\x18\xb6\xc3\xaaP \x01(\x0b\x32+.handsDet.PacketFrequencyCalculatorOptions')
  ,
  dependencies=[handsDet_dot_framework_dot_calculator__pb2.DESCRIPTOR,])




_PACKETFREQUENCYCALCULATOROPTIONS = _descriptor.Descriptor(
  name='PacketFrequencyCalculatorOptions',
  full_name='handsDet.PacketFrequencyCalculatorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_window_sec', full_name='handsDet.PacketFrequencyCalculatorOptions.time_window_sec', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(3),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='handsDet.PacketFrequencyCalculatorOptions.label', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='handsDet.PacketFrequencyCalculatorOptions.ext', index=0,
      number=168468918, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=282,
)

DESCRIPTOR.message_types_by_name['PacketFrequencyCalculatorOptions'] = _PACKETFREQUENCYCALCULATOROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PacketFrequencyCalculatorOptions = _reflection.GeneratedProtocolMessageType('PacketFrequencyCalculatorOptions', (_message.Message,), dict(
  DESCRIPTOR = _PACKETFREQUENCYCALCULATOROPTIONS,
  __module__ = 'handsDet.calculators.util.packet_frequency_calculator_pb2'
  # @@protoc_insertion_point(class_scope:handsDet.PacketFrequencyCalculatorOptions)
  ))
_sym_db.RegisterMessage(PacketFrequencyCalculatorOptions)

_PACKETFREQUENCYCALCULATOROPTIONS.extensions_by_name['ext'].message_type = _PACKETFREQUENCYCALCULATOROPTIONS
handsDet_dot_framework_dot_calculator__options__pb2.CalculatorOptions.RegisterExtension(_PACKETFREQUENCYCALCULATOROPTIONS.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
