# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: handsDet/framework/formats/detection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from handsDet.framework.formats import location_data_pb2 as handsDet_dot_framework_dot_formats_dot_location__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='handsDet/framework/formats/detection.proto',
  package='handsDet',
  syntax='proto2',
  serialized_options=_b('\n\"com.google.handsDet.formats.protoB\016DetectionProto'),
  serialized_pb=_b('\n+handsDet/framework/formats/detection.proto\x12\thandsDet\x1a/handsDet/framework/formats/location_data.proto\"\xde\x02\n\tDetection\x12\r\n\x05label\x18\x01 \x03(\t\x12\x14\n\x08label_id\x18\x02 \x03(\x05\x42\x02\x10\x01\x12\x11\n\x05score\x18\x03 \x03(\x02\x42\x02\x10\x01\x12.\n\rlocation_data\x18\x04 \x01(\x0b\x32\x17.handsDet.LocationData\x12\x13\n\x0b\x66\x65\x61ture_tag\x18\x05 \x01(\t\x12\x10\n\x08track_id\x18\x06 \x01(\t\x12\x14\n\x0c\x64\x65tection_id\x18\x07 \x01(\x03\x12G\n\x15\x61ssociated_detections\x18\x08 \x03(\x0b\x32(.handsDet.Detection.AssociatedDetection\x12\x14\n\x0c\x64isplay_name\x18\t \x03(\t\x12\x16\n\x0etimestamp_usec\x18\n \x01(\x03\x1a\x35\n\x13\x41ssociatedDetection\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nconfidence\x18\x02 \x01(\x02\"8\n\rDetectionList\x12\'\n\tdetection\x18\x01 \x03(\x0b\x32\x14.handsDet.DetectionB4\n\"com.google.handsDet.formats.protoB\x0e\x44\x65tectionProto')
  ,
  dependencies=[handsDet_dot_framework_dot_formats_dot_location__data__pb2.DESCRIPTOR,])




_DETECTION_ASSOCIATEDDETECTION = _descriptor.Descriptor(
  name='AssociatedDetection',
  full_name='handsDet.Detection.AssociatedDetection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='handsDet.Detection.AssociatedDetection.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='handsDet.Detection.AssociatedDetection.confidence', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=458,
)

_DETECTION = _descriptor.Descriptor(
  name='Detection',
  full_name='handsDet.Detection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='handsDet.Detection.label', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label_id', full_name='handsDet.Detection.label_id', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='handsDet.Detection.score', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location_data', full_name='handsDet.Detection.location_data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feature_tag', full_name='handsDet.Detection.feature_tag', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='track_id', full_name='handsDet.Detection.track_id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detection_id', full_name='handsDet.Detection.detection_id', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='associated_detections', full_name='handsDet.Detection.associated_detections', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='display_name', full_name='handsDet.Detection.display_name', index=8,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp_usec', full_name='handsDet.Detection.timestamp_usec', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DETECTION_ASSOCIATEDDETECTION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=458,
)


_DETECTIONLIST = _descriptor.Descriptor(
  name='DetectionList',
  full_name='handsDet.DetectionList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detection', full_name='handsDet.DetectionList.detection', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=460,
  serialized_end=516,
)

_DETECTION_ASSOCIATEDDETECTION.containing_type = _DETECTION
_DETECTION.fields_by_name['location_data'].message_type = handsDet_dot_framework_dot_formats_dot_location__data__pb2._LOCATIONDATA
_DETECTION.fields_by_name['associated_detections'].message_type = _DETECTION_ASSOCIATEDDETECTION
_DETECTIONLIST.fields_by_name['detection'].message_type = _DETECTION
DESCRIPTOR.message_types_by_name['Detection'] = _DETECTION
DESCRIPTOR.message_types_by_name['DetectionList'] = _DETECTIONLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Detection = _reflection.GeneratedProtocolMessageType('Detection', (_message.Message,), dict(

  AssociatedDetection = _reflection.GeneratedProtocolMessageType('AssociatedDetection', (_message.Message,), dict(
    DESCRIPTOR = _DETECTION_ASSOCIATEDDETECTION,
    __module__ = 'handsDet.framework.formats.detection_pb2'
    # @@protoc_insertion_point(class_scope:handsDet.Detection.AssociatedDetection)
    ))
  ,
  DESCRIPTOR = _DETECTION,
  __module__ = 'handsDet.framework.formats.detection_pb2'
  # @@protoc_insertion_point(class_scope:handsDet.Detection)
  ))
_sym_db.RegisterMessage(Detection)
_sym_db.RegisterMessage(Detection.AssociatedDetection)

DetectionList = _reflection.GeneratedProtocolMessageType('DetectionList', (_message.Message,), dict(
  DESCRIPTOR = _DETECTIONLIST,
  __module__ = 'handsDet.framework.formats.detection_pb2'
  # @@protoc_insertion_point(class_scope:handsDet.DetectionList)
  ))
_sym_db.RegisterMessage(DetectionList)


DESCRIPTOR._options = None
_DETECTION.fields_by_name['label_id']._options = None
_DETECTION.fields_by_name['score']._options = None
# @@protoc_insertion_point(module_scope)
