# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: handsDet/util/tracking/box_tracker.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from handsDet.util.tracking import tracking_pb2 as handsDet_dot_util_dot_tracking_dot_tracking__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='handsDet/util/tracking/box_tracker.proto',
  package='handsDet',
  syntax='proto2',
  serialized_options=_b('\n\035com.google.handsDet.trackingB\017BoxTrackerProto'),
  serialized_pb=_b('\n)handsDet/util/tracking/box_tracker.proto\x12\thandsDet\x1a&handsDet/util/tracking/tracking.proto\"\x86\x02\n\x11\x42oxTrackerOptions\x12%\n\x17\x63\x61\x63hing_chunk_size_msec\x18\x01 \x01(\x05:\x04\x32\x35\x30\x30\x12%\n\x11\x63\x61\x63he_file_format\x18\x02 \x01(\t:\nchunk_%04d\x12\x1f\n\x14num_tracking_workers\x18\x03 \x01(\x05:\x01\x38\x12&\n\x17read_chunk_timeout_msec\x18\x04 \x01(\x05:\x05\x36\x30\x30\x30\x30\x12!\n\x12record_path_states\x18\x05 \x01(\x08:\x05\x66\x61lse\x12\x37\n\x12track_step_options\x18\x06 \x01(\x0b\x32\x1b.handsDet.TrackStepOptions\"\xa7\x02\n\rTimedBoxProto\x12\x0b\n\x03top\x18\x01 \x01(\x02\x12\x0c\n\x04left\x18\x02 \x01(\x02\x12\x0e\n\x06\x62ottom\x18\x03 \x01(\x02\x12\r\n\x05right\x18\x04 \x01(\x02\x12\x10\n\x08rotation\x18\x07 \x01(\x02\x12,\n\x04quad\x18\t \x01(\x0b\x32\x1e.handsDet.MotionBoxState.Quad\x12\x14\n\ttime_msec\x18\x05 \x01(\x03:\x01\x30\x12\x0e\n\x02id\x18\x06 \x01(\x05:\x02-1\x12\r\n\x05label\x18\r \x01(\t\x12\x12\n\nconfidence\x18\x08 \x01(\x02\x12\x14\n\x0c\x61spect_ratio\x18\n \x01(\x02\x12\x1c\n\rreacquisition\x18\x0b \x01(\x08:\x05\x66\x61lse\x12\x1f\n\x10request_grouping\x18\x0c \x01(\x08:\x05\x66\x61lse\":\n\x11TimedBoxProtoList\x12%\n\x03\x62ox\x18\x01 \x03(\x0b\x32\x18.handsDet.TimedBoxProtoB0\n\x1d\x63om.google.handsDet.trackingB\x0f\x42oxTrackerProto')
  ,
  dependencies=[handsDet_dot_util_dot_tracking_dot_tracking__pb2.DESCRIPTOR,])




_BOXTRACKEROPTIONS = _descriptor.Descriptor(
  name='BoxTrackerOptions',
  full_name='handsDet.BoxTrackerOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='caching_chunk_size_msec', full_name='handsDet.BoxTrackerOptions.caching_chunk_size_msec', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=2500,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cache_file_format', full_name='handsDet.BoxTrackerOptions.cache_file_format', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("chunk_%04d").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_tracking_workers', full_name='handsDet.BoxTrackerOptions.num_tracking_workers', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=8,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='read_chunk_timeout_msec', full_name='handsDet.BoxTrackerOptions.read_chunk_timeout_msec', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=60000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='record_path_states', full_name='handsDet.BoxTrackerOptions.record_path_states', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='track_step_options', full_name='handsDet.BoxTrackerOptions.track_step_options', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=359,
)


_TIMEDBOXPROTO = _descriptor.Descriptor(
  name='TimedBoxProto',
  full_name='handsDet.TimedBoxProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='top', full_name='handsDet.TimedBoxProto.top', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='left', full_name='handsDet.TimedBoxProto.left', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bottom', full_name='handsDet.TimedBoxProto.bottom', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='right', full_name='handsDet.TimedBoxProto.right', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='handsDet.TimedBoxProto.rotation', index=4,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quad', full_name='handsDet.TimedBoxProto.quad', index=5,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_msec', full_name='handsDet.TimedBoxProto.time_msec', index=6,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='handsDet.TimedBoxProto.id', index=7,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='handsDet.TimedBoxProto.label', index=8,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='handsDet.TimedBoxProto.confidence', index=9,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aspect_ratio', full_name='handsDet.TimedBoxProto.aspect_ratio', index=10,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reacquisition', full_name='handsDet.TimedBoxProto.reacquisition', index=11,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_grouping', full_name='handsDet.TimedBoxProto.request_grouping', index=12,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=657,
)


_TIMEDBOXPROTOLIST = _descriptor.Descriptor(
  name='TimedBoxProtoList',
  full_name='handsDet.TimedBoxProtoList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='box', full_name='handsDet.TimedBoxProtoList.box', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=659,
  serialized_end=717,
)

_BOXTRACKEROPTIONS.fields_by_name['track_step_options'].message_type = handsDet_dot_util_dot_tracking_dot_tracking__pb2._TRACKSTEPOPTIONS
_TIMEDBOXPROTO.fields_by_name['quad'].message_type = handsDet_dot_util_dot_tracking_dot_tracking__pb2._MOTIONBOXSTATE_QUAD
_TIMEDBOXPROTOLIST.fields_by_name['box'].message_type = _TIMEDBOXPROTO
DESCRIPTOR.message_types_by_name['BoxTrackerOptions'] = _BOXTRACKEROPTIONS
DESCRIPTOR.message_types_by_name['TimedBoxProto'] = _TIMEDBOXPROTO
DESCRIPTOR.message_types_by_name['TimedBoxProtoList'] = _TIMEDBOXPROTOLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BoxTrackerOptions = _reflection.GeneratedProtocolMessageType('BoxTrackerOptions', (_message.Message,), dict(
  DESCRIPTOR = _BOXTRACKEROPTIONS,
  __module__ = 'handsDet.util.tracking.box_tracker_pb2'
  # @@protoc_insertion_point(class_scope:handsDet.BoxTrackerOptions)
  ))
_sym_db.RegisterMessage(BoxTrackerOptions)

TimedBoxProto = _reflection.GeneratedProtocolMessageType('TimedBoxProto', (_message.Message,), dict(
  DESCRIPTOR = _TIMEDBOXPROTO,
  __module__ = 'handsDet.util.tracking.box_tracker_pb2'
  # @@protoc_insertion_point(class_scope:handsDet.TimedBoxProto)
  ))
_sym_db.RegisterMessage(TimedBoxProto)

TimedBoxProtoList = _reflection.GeneratedProtocolMessageType('TimedBoxProtoList', (_message.Message,), dict(
  DESCRIPTOR = _TIMEDBOXPROTOLIST,
  __module__ = 'handsDet.util.tracking.box_tracker_pb2'
  # @@protoc_insertion_point(class_scope:handsDet.TimedBoxProtoList)
  ))
_sym_db.RegisterMessage(TimedBoxProtoList)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
