# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: handsDet/framework/stream_handler/default_input_stream_handler.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from handsDet.framework import handsDet_options_pb2 as handsDet_dot_framework_dot_handsDet__options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='handsDet/framework/stream_handler/default_input_stream_handler.proto',
  package='handsDet',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\nEhandsDet/framework/stream_handler/default_input_stream_handler.proto\x12\thandsDet\x1a+handsDet/framework/handsDet_options.proto\"\x93\x01\n DefaultInputStreamHandlerOptions\x12\x15\n\nbatch_size\x18\x01 \x01(\x05:\x01\x31\x32X\n\x03\x65xt\x12\x1b.handsDet.MediaPipeOptions\x18\xf5\xed\xacN \x01(\x0b\x32+.handsDet.DefaultInputStreamHandlerOptions')
  ,
  dependencies=[handsDet_dot_framework_dot_handsDet__options__pb2.DESCRIPTOR,])




_DEFAULTINPUTSTREAMHANDLEROPTIONS = _descriptor.Descriptor(
  name='DefaultInputStreamHandlerOptions',
  full_name='handsDet.DefaultInputStreamHandlerOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='handsDet.DefaultInputStreamHandlerOptions.batch_size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='handsDet.DefaultInputStreamHandlerOptions.ext', index=0,
      number=164312821, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=277,
)

DESCRIPTOR.message_types_by_name['DefaultInputStreamHandlerOptions'] = _DEFAULTINPUTSTREAMHANDLEROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DefaultInputStreamHandlerOptions = _reflection.GeneratedProtocolMessageType('DefaultInputStreamHandlerOptions', (_message.Message,), dict(
  DESCRIPTOR = _DEFAULTINPUTSTREAMHANDLEROPTIONS,
  __module__ = 'handsDet.framework.stream_handler.default_input_stream_handler_pb2'
  # @@protoc_insertion_point(class_scope:handsDet.DefaultInputStreamHandlerOptions)
  ))
_sym_db.RegisterMessage(DefaultInputStreamHandlerOptions)

_DEFAULTINPUTSTREAMHANDLEROPTIONS.extensions_by_name['ext'].message_type = _DEFAULTINPUTSTREAMHANDLEROPTIONS
handsDet_dot_framework_dot_handsDet__options__pb2.MediaPipeOptions.RegisterExtension(_DEFAULTINPUTSTREAMHANDLEROPTIONS.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
