# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: handsDet/framework/stream_handler/fixed_size_input_stream_handler.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from handsDet.framework import handsDet_options_pb2 as handsDet_dot_framework_dot_handsDet__options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='handsDet/framework/stream_handler/fixed_size_input_stream_handler.proto',
  package='handsDet',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\nHhandsDet/framework/stream_handler/fixed_size_input_stream_handler.proto\x12\thandsDet\x1a+handsDet/framework/handsDet_options.proto\"\xdc\x01\n\"FixedSizeInputStreamHandlerOptions\x12\x1d\n\x12trigger_queue_size\x18\x01 \x01(\x05:\x01\x32\x12\x1c\n\x11target_queue_size\x18\x02 \x01(\x05:\x01\x31\x12\x1d\n\x0e\x66ixed_min_size\x18\x03 \x01(\x08:\x05\x66\x61lse2Z\n\x03\x65xt\x12\x1b.handsDet.MediaPipeOptions\x18\xbf\xe9\xfa; \x01(\x0b\x32-.handsDet.FixedSizeInputStreamHandlerOptions')
  ,
  dependencies=[handsDet_dot_framework_dot_handsDet__options__pb2.DESCRIPTOR,])




_FIXEDSIZEINPUTSTREAMHANDLEROPTIONS = _descriptor.Descriptor(
  name='FixedSizeInputStreamHandlerOptions',
  full_name='handsDet.FixedSizeInputStreamHandlerOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trigger_queue_size', full_name='handsDet.FixedSizeInputStreamHandlerOptions.trigger_queue_size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_queue_size', full_name='handsDet.FixedSizeInputStreamHandlerOptions.target_queue_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fixed_min_size', full_name='handsDet.FixedSizeInputStreamHandlerOptions.fixed_min_size', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='handsDet.FixedSizeInputStreamHandlerOptions.ext', index=0,
      number=125744319, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=353,
)

DESCRIPTOR.message_types_by_name['FixedSizeInputStreamHandlerOptions'] = _FIXEDSIZEINPUTSTREAMHANDLEROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FixedSizeInputStreamHandlerOptions = _reflection.GeneratedProtocolMessageType('FixedSizeInputStreamHandlerOptions', (_message.Message,), dict(
  DESCRIPTOR = _FIXEDSIZEINPUTSTREAMHANDLEROPTIONS,
  __module__ = 'handsDet.framework.stream_handler.fixed_size_input_stream_handler_pb2'
  # @@protoc_insertion_point(class_scope:handsDet.FixedSizeInputStreamHandlerOptions)
  ))
_sym_db.RegisterMessage(FixedSizeInputStreamHandlerOptions)

_FIXEDSIZEINPUTSTREAMHANDLEROPTIONS.extensions_by_name['ext'].message_type = _FIXEDSIZEINPUTSTREAMHANDLEROPTIONS
handsDet_dot_framework_dot_handsDet__options__pb2.MediaPipeOptions.RegisterExtension(_FIXEDSIZEINPUTSTREAMHANDLEROPTIONS.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
