# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: handsDet/framework/stream_handler/timestamp_align_input_stream_handler.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from handsDet.framework import handsDet_options_pb2 as handsDet_dot_framework_dot_handsDet__options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='handsDet/framework/stream_handler/timestamp_align_input_stream_handler.proto',
  package='handsDet',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\nMhandsDet/framework/stream_handler/timestamp_align_input_stream_handler.proto\x12\thandsDet\x1a+handsDet/framework/handsDet_options.proto\"\xac\x01\n\'TimestampAlignInputStreamHandlerOptions\x12 \n\x18timestamp_base_tag_index\x18\x01 \x01(\t2_\n\x03\x65xt\x12\x1b.handsDet.MediaPipeOptions\x18\x93\x8b\xd3Z \x01(\x0b\x32\x32.handsDet.TimestampAlignInputStreamHandlerOptions')
  ,
  dependencies=[handsDet_dot_framework_dot_handsDet__options__pb2.DESCRIPTOR,])




_TIMESTAMPALIGNINPUTSTREAMHANDLEROPTIONS = _descriptor.Descriptor(
  name='TimestampAlignInputStreamHandlerOptions',
  full_name='handsDet.TimestampAlignInputStreamHandlerOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp_base_tag_index', full_name='handsDet.TimestampAlignInputStreamHandlerOptions.timestamp_base_tag_index', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='handsDet.TimestampAlignInputStreamHandlerOptions.ext', index=0,
      number=190104979, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=310,
)

DESCRIPTOR.message_types_by_name['TimestampAlignInputStreamHandlerOptions'] = _TIMESTAMPALIGNINPUTSTREAMHANDLEROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimestampAlignInputStreamHandlerOptions = _reflection.GeneratedProtocolMessageType('TimestampAlignInputStreamHandlerOptions', (_message.Message,), dict(
  DESCRIPTOR = _TIMESTAMPALIGNINPUTSTREAMHANDLEROPTIONS,
  __module__ = 'handsDet.framework.stream_handler.timestamp_align_input_stream_handler_pb2'
  # @@protoc_insertion_point(class_scope:handsDet.TimestampAlignInputStreamHandlerOptions)
  ))
_sym_db.RegisterMessage(TimestampAlignInputStreamHandlerOptions)

_TIMESTAMPALIGNINPUTSTREAMHANDLEROPTIONS.extensions_by_name['ext'].message_type = _TIMESTAMPALIGNINPUTSTREAMHANDLEROPTIONS
handsDet_dot_framework_dot_handsDet__options__pb2.MediaPipeOptions.RegisterExtension(_TIMESTAMPALIGNINPUTSTREAMHANDLEROPTIONS.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
